---
name: Backrest
version: 0.0.1-dev
slug: backrest
description: Backrest
url: https://github.com/brmo/hassio-addons/tree/main/backrest
init: false
arch:
  - amd64
ingress: true
map:
  - homeassistant_config
  - share
startup: system
boot: auto
ports:
  - 9898:9898
image: brmo/home-assistant-addon-{arch}-backrest
